[package]
name = "rlab"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["rlib", "staticlib"]

[dependencies]
tokio = { version = "1", features = ["full"] }
gimli = { version = "0.29.0", features = ["read"] }
object = "0.36.0"
memmap2 = "0.9.4"
anyhow = "1.0"